services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    environment:
      TZ: Europe/Copenhagen
    ports:
      - 8123:8123
  monitor:
    container_name: monitor
    build:
      context: .
      target: final
    depends_on:
      - homeassistant
    environment:
      - BASE_URL=http://localhost:8123
      - TOKEN=USERAPITOKEN