
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean: !include simulated/input_booleans.yaml
input_number: !include simulated/input_numbers.yaml
input_select: !include simulated/input_selects.yaml
template: !include simulated/templates.yaml

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.0.0/16
        - 10.27.0.0/16
      allow_bypass_login: true 
    - type: homeassistant