//! Module for the lexer and parser for `Cfg`
//! WARNING: this file has been generated by
//! Hime Parser Generator 4.4.0

use hime_redist::ast::{AstImpl, AstNode};
use hime_redist::errors::ParseErrors;
use hime_redist::lexers::automaton::Automaton;
use hime_redist::lexers::impls::ContextFreeLexer;
use hime_redist::lexers::Lexer;
use hime_redist::parsers::lrk::LRkAutomaton;
use hime_redist::parsers::lrk::LRkParser;
use hime_redist::parsers::Parser;
use hime_redist::result::{ParseResult, ParseResultAst};
use hime_redist::symbols::SemanticBody;
use hime_redist::symbols::SemanticElementTrait;
use hime_redist::symbols::Symbol;
use hime_redist::text::Text;
use hime_redist::tokens::TokenRepository;

/// Static resource for the serialized lexer automaton
static LEXER_AUTOMATON: &[u8] = include_bytes!("cfg_lexer.bin");

/// The unique identifier for terminal `SEPARATOR`
pub const ID_TERMINAL_SEPARATOR: u32 = 0x0004;
/// The unique identifier for terminal `NUMBER`
pub const ID_TERMINAL_NUMBER: u32 = 0x0007;
/// The unique identifier for terminal `STRING`
pub const ID_TERMINAL_STRING: u32 = 0x0008;
/// The unique identifier for terminal `TIMEUNIT`
pub const ID_TERMINAL_TIMEUNIT: u32 = 0x0009;
/// The unique identifier for terminal `POWERUNIT`
pub const ID_TERMINAL_POWERUNIT: u32 = 0x000A;
/// The unique identifier for terminal `BOOL`
pub const ID_TERMINAL_BOOL: u32 = 0x000B;
/// The unique identifier for terminal `TIME`
pub const ID_TERMINAL_TIME: u32 = 0x000C;

/// The unique identifier for the default context
pub const CONTEXT_DEFAULT: u16 = 0;

/// The collection of terminals matched by this lexer
/// The terminals are in an order consistent with the automaton,
/// so that terminal indices in the automaton can be used to retrieve the terminals in this table
pub const TERMINALS: &[Symbol] = &[
    Symbol {
        id: 0x0001,
        name: "ε"
    },
    Symbol {
        id: 0x0002,
        name: "$"
    },
    Symbol {
        id: 0x0004,
        name: "SEPARATOR"
    },
    Symbol {
        id: 0x0007,
        name: "NUMBER"
    },
    Symbol {
        id: 0x0008,
        name: "STRING"
    },
    Symbol {
        id: 0x0009,
        name: "TIMEUNIT"
    },
    Symbol {
        id: 0x000A,
        name: "POWERUNIT"
    },
    Symbol {
        id: 0x000B,
        name: "BOOL"
    },
    Symbol {
        id: 0x000C,
        name: "TIME"
    },
    Symbol {
        id: 0x0029,
        name: ";"
    },
    Symbol {
        id: 0x002B,
        name: "!"
    },
    Symbol {
        id: 0x002C,
        name: "always"
    },
    Symbol {
        id: 0x002D,
        name: "eventually"
    },
    Symbol {
        id: 0x002E,
        name: "["
    },
    Symbol {
        id: 0x002F,
        name: ","
    },
    Symbol {
        id: 0x0030,
        name: "]"
    },
    Symbol {
        id: 0x0031,
        name: "+"
    },
    Symbol {
        id: 0x0032,
        name: "-"
    },
    Symbol {
        id: 0x0033,
        name: "*"
    },
    Symbol {
        id: 0x0034,
        name: "/"
    },
    Symbol {
        id: 0x0035,
        name: "%"
    },
    Symbol {
        id: 0x0036,
        name: "("
    },
    Symbol {
        id: 0x0037,
        name: ")"
    },
    Symbol {
        id: 0x0038,
        name: "->"
    },
    Symbol {
        id: 0x0039,
        name: "|"
    },
    Symbol {
        id: 0x003A,
        name: "&"
    },
    Symbol {
        id: 0x003B,
        name: "="
    },
    Symbol {
        id: 0x003C,
        name: "<="
    },
    Symbol {
        id: 0x003D,
        name: ">="
    },
    Symbol {
        id: 0x003E,
        name: "!="
    },
    Symbol {
        id: 0x003F,
        name: "<"
    },
    Symbol {
        id: 0x0040,
        name: ">"
    },
    Symbol {
        id: 0x0041,
        name: "sumtime"
    },
    Symbol {
        id: 0x0042,
        name: "avgtime"
    },
    Symbol {
        id: 0x0043,
        name: "counttime"
    },
    Symbol {
        id: 0x0044,
        name: "foreach"
    },
    Symbol {
        id: 0x0045,
        name: "sum"
    },
    Symbol {
        id: 0x0046,
        name: "avg"
    },
    Symbol {
        id: 0x0047,
        name: "count"
    },
    Symbol {
        id: 0x0048,
        name: "active"
    },
    Symbol {
        id: 0x0049,
        name: "power"
    },
    Symbol {
        id: 0x004A,
        name: "name"
    }
];

/// Creates a new lexer
fn new_lexer<'a: 'b, 'b, 'c>(
    repository: TokenRepository<'a, 'b, 'c>,
    errors: &'c mut ParseErrors<'a>
) -> Lexer<'a, 'b, 'c> {
    let automaton = Automaton::new(LEXER_AUTOMATON);
    Lexer::ContextFree(ContextFreeLexer::new(repository, errors, automaton, 0x0004))
}

/// Static resource for the serialized parser automaton
static PARSER_AUTOMATON: &[u8] = include_bytes!("cfg_parser.bin");

/// The unique identifier for variable `Program`
pub const ID_VARIABLE_PROGRAM: u32 = 0x000D;
/// The unique identifier for variable `MTLStart`
pub const ID_VARIABLE_MTLSTART: u32 = 0x000E;
/// The unique identifier for variable `Interval`
pub const ID_VARIABLE_INTERVAL: u32 = 0x000F;
/// The unique identifier for variable `ExprA`
pub const ID_VARIABLE_EXPR_A: u32 = 0x0010;
/// The unique identifier for variable `ExprA1`
pub const ID_VARIABLE_EXPR_A1: u32 = 0x0011;
/// The unique identifier for variable `ExprA2`
pub const ID_VARIABLE_EXPR_A2: u32 = 0x0012;
/// The unique identifier for variable `ExprA3`
pub const ID_VARIABLE_EXPR_A3: u32 = 0x0013;
/// The unique identifier for variable `Expr`
pub const ID_VARIABLE_EXPR: u32 = 0x0014;
/// The unique identifier for variable `ExprV1`
pub const ID_VARIABLE_EXPR_V1: u32 = 0x0015;
/// The unique identifier for variable `ExprV2`
pub const ID_VARIABLE_EXPR_V2: u32 = 0x0016;
/// The unique identifier for variable `ExprV3`
pub const ID_VARIABLE_EXPR_V3: u32 = 0x0017;
/// The unique identifier for variable `ExprV4`
pub const ID_VARIABLE_EXPR_V4: u32 = 0x0018;
/// The unique identifier for variable `ExprV5`
pub const ID_VARIABLE_EXPR_V5: u32 = 0x0019;
/// The unique identifier for variable `ExprV6`
pub const ID_VARIABLE_EXPR_V6: u32 = 0x001A;
/// The unique identifier for variable `ExprV7`
pub const ID_VARIABLE_EXPR_V7: u32 = 0x001B;
/// The unique identifier for variable `ExprV8`
pub const ID_VARIABLE_EXPR_V8: u32 = 0x001C;
/// The unique identifier for variable `Function`
pub const ID_VARIABLE_FUNCTION: u32 = 0x001D;
/// The unique identifier for variable `Aggregate`
pub const ID_VARIABLE_AGGREGATE: u32 = 0x001E;
/// The unique identifier for variable `FunctionExpr`
pub const ID_VARIABLE_FUNCTION_EXPR: u32 = 0x001F;
/// The unique identifier for variable `FunctionExprV1`
pub const ID_VARIABLE_FUNCTION_EXPR_V1: u32 = 0x0020;
/// The unique identifier for variable `FunctionExprV2`
pub const ID_VARIABLE_FUNCTION_EXPR_V2: u32 = 0x0021;
/// The unique identifier for variable `FunctionExprV3`
pub const ID_VARIABLE_FUNCTION_EXPR_V3: u32 = 0x0022;
/// The unique identifier for variable `FunctionExprV4`
pub const ID_VARIABLE_FUNCTION_EXPR_V4: u32 = 0x0023;
/// The unique identifier for variable `FunctionExprV5`
pub const ID_VARIABLE_FUNCTION_EXPR_V5: u32 = 0x0024;
/// The unique identifier for variable `FunctionExprV6`
pub const ID_VARIABLE_FUNCTION_EXPR_V6: u32 = 0x0025;
/// The unique identifier for variable `FunctionExprV7`
pub const ID_VARIABLE_FUNCTION_EXPR_V7: u32 = 0x0026;
/// The unique identifier for variable `FunctionExprV8`
pub const ID_VARIABLE_FUNCTION_EXPR_V8: u32 = 0x0027;
/// The unique identifier for variable `Member`
pub const ID_VARIABLE_MEMBER: u32 = 0x0028;


/// The collection of variables matched by this parser
/// The variables are in an order consistent with the automaton,
/// so that variable indices in the automaton can be used to retrieve the variables in this table
pub const VARIABLES: &[Symbol] = &[
    Symbol {
        id: 0x000D,
        name: "Program"
    },
    Symbol {
        id: 0x000E,
        name: "MTLStart"
    },
    Symbol {
        id: 0x000F,
        name: "Interval"
    },
    Symbol {
        id: 0x0010,
        name: "ExprA"
    },
    Symbol {
        id: 0x0011,
        name: "ExprA1"
    },
    Symbol {
        id: 0x0012,
        name: "ExprA2"
    },
    Symbol {
        id: 0x0013,
        name: "ExprA3"
    },
    Symbol {
        id: 0x0014,
        name: "Expr"
    },
    Symbol {
        id: 0x0015,
        name: "ExprV1"
    },
    Symbol {
        id: 0x0016,
        name: "ExprV2"
    },
    Symbol {
        id: 0x0017,
        name: "ExprV3"
    },
    Symbol {
        id: 0x0018,
        name: "ExprV4"
    },
    Symbol {
        id: 0x0019,
        name: "ExprV5"
    },
    Symbol {
        id: 0x001A,
        name: "ExprV6"
    },
    Symbol {
        id: 0x001B,
        name: "ExprV7"
    },
    Symbol {
        id: 0x001C,
        name: "ExprV8"
    },
    Symbol {
        id: 0x001D,
        name: "Function"
    },
    Symbol {
        id: 0x001E,
        name: "Aggregate"
    },
    Symbol {
        id: 0x001F,
        name: "FunctionExpr"
    },
    Symbol {
        id: 0x0020,
        name: "FunctionExprV1"
    },
    Symbol {
        id: 0x0021,
        name: "FunctionExprV2"
    },
    Symbol {
        id: 0x0022,
        name: "FunctionExprV3"
    },
    Symbol {
        id: 0x0023,
        name: "FunctionExprV4"
    },
    Symbol {
        id: 0x0024,
        name: "FunctionExprV5"
    },
    Symbol {
        id: 0x0025,
        name: "FunctionExprV6"
    },
    Symbol {
        id: 0x0026,
        name: "FunctionExprV7"
    },
    Symbol {
        id: 0x0027,
        name: "FunctionExprV8"
    },
    Symbol {
        id: 0x0028,
        name: "Member"
    },
    Symbol {
        id: 0x002A,
        name: "__V42"
    },
    Symbol {
        id: 0x004B,
        name: "__VAxiom"
    }
];

/// The collection of virtuals matched by this parser
/// The virtuals are in an order consistent with the automaton,
/// so that virtual indices in the automaton can be used to retrieve the virtuals in this table
pub const VIRTUALS: &[Symbol] = &[

];

/// Parses the specified string with this parser
#[must_use]
pub fn parse_str(input: &str) -> ParseResult<'static, '_, 'static, AstImpl> {
    let text = Text::from_str(input);
    parse_text(text)
}

/// Parses the specified string with this parser
#[must_use]
pub fn parse_string(input: String) -> ParseResultAst {
    let text = Text::from_string(input);
    parse_text(text)
}

/// Parses the specified stream of UTF-8 with this parser
///
/// # Errors
///
/// Return an `std::io::Error` when reading the stream as UTF-8 fails
pub fn parse_utf8_stream(input: &mut dyn std::io::Read) -> Result<ParseResultAst, std::io::Error> {
    let text = Text::from_utf8_stream(input)?;
    Ok(parse_text(text))
}

/// Parses the specified text with this parser
fn parse_text<'t>(text: Text<'t>) -> ParseResult<'static, 't, 'static, AstImpl> {
    parse_text_with(text, TERMINALS, VARIABLES, VIRTUALS)
}

/// Parses the specified text with this parser
fn parse_text_with<'s, 't, 'a>(
    text: Text<'t>,
    terminals: &'a [Symbol<'s>],
    variables: &'a [Symbol<'s>],
    virtuals: &'a [Symbol<'s>],
) -> ParseResult<'s, 't, 'a, AstImpl> {
    let mut my_actions = |_index: usize, _head: Symbol, _body: &dyn SemanticBody| {};
    let mut result = ParseResult::<AstImpl>::new(terminals, variables, virtuals, text);
    {
        let data = result.get_parsing_data();
        let mut lexer = new_lexer(data.0, data.1);
        let automaton = LRkAutomaton::new(PARSER_AUTOMATON);
        let mut parser = LRkParser::new(&mut lexer, variables, virtuals, automaton, data.2, &mut my_actions);
        parser.parse();
    }
    result
}

/// Visitor interface
#[allow(unused_variables)]
pub trait Visitor {
    fn on_terminal_separator(&self, node: &AstNode) {}
    fn on_terminal_number(&self, node: &AstNode) {}
    fn on_terminal_string(&self, node: &AstNode) {}
    fn on_terminal_timeunit(&self, node: &AstNode) {}
    fn on_terminal_powerunit(&self, node: &AstNode) {}
    fn on_terminal_bool(&self, node: &AstNode) {}
    fn on_terminal_time(&self, node: &AstNode) {}
    fn on_variable_program(&self, node: &AstNode) {}
    fn on_variable_mtlstart(&self, node: &AstNode) {}
    fn on_variable_interval(&self, node: &AstNode) {}
    fn on_variable_expr_a(&self, node: &AstNode) {}
    fn on_variable_expr_a1(&self, node: &AstNode) {}
    fn on_variable_expr_a2(&self, node: &AstNode) {}
    fn on_variable_expr_a3(&self, node: &AstNode) {}
    fn on_variable_expr(&self, node: &AstNode) {}
    fn on_variable_expr_v1(&self, node: &AstNode) {}
    fn on_variable_expr_v2(&self, node: &AstNode) {}
    fn on_variable_expr_v3(&self, node: &AstNode) {}
    fn on_variable_expr_v4(&self, node: &AstNode) {}
    fn on_variable_expr_v5(&self, node: &AstNode) {}
    fn on_variable_expr_v6(&self, node: &AstNode) {}
    fn on_variable_expr_v7(&self, node: &AstNode) {}
    fn on_variable_expr_v8(&self, node: &AstNode) {}
    fn on_variable_function(&self, node: &AstNode) {}
    fn on_variable_aggregate(&self, node: &AstNode) {}
    fn on_variable_function_expr(&self, node: &AstNode) {}
    fn on_variable_function_expr_v1(&self, node: &AstNode) {}
    fn on_variable_function_expr_v2(&self, node: &AstNode) {}
    fn on_variable_function_expr_v3(&self, node: &AstNode) {}
    fn on_variable_function_expr_v4(&self, node: &AstNode) {}
    fn on_variable_function_expr_v5(&self, node: &AstNode) {}
    fn on_variable_function_expr_v6(&self, node: &AstNode) {}
    fn on_variable_function_expr_v7(&self, node: &AstNode) {}
    fn on_variable_function_expr_v8(&self, node: &AstNode) {}
    fn on_variable_member(&self, node: &AstNode) {}
}

/// Walk the AST of a result using a visitor
pub fn visit(result: &ParseResult<AstImpl>, visitor: &dyn Visitor) {
    let ast = result.get_ast();
    let root = ast.get_root();
    visit_ast_node(root, visitor);
}

/// Walk the sub-AST from the specified node using a visitor
pub fn visit_ast_node(node: AstNode, visitor: &dyn Visitor) {
    let children = node.children();
    for child in children.iter() {
        visit_ast_node(child, visitor);
    }
    match node.get_symbol().id {
        0x0004 => visitor.on_terminal_separator(&node),
        0x0007 => visitor.on_terminal_number(&node),
        0x0008 => visitor.on_terminal_string(&node),
        0x0009 => visitor.on_terminal_timeunit(&node),
        0x000A => visitor.on_terminal_powerunit(&node),
        0x000B => visitor.on_terminal_bool(&node),
        0x000C => visitor.on_terminal_time(&node),
        0x000D => visitor.on_variable_program(&node),
        0x000E => visitor.on_variable_mtlstart(&node),
        0x000F => visitor.on_variable_interval(&node),
        0x0010 => visitor.on_variable_expr_a(&node),
        0x0011 => visitor.on_variable_expr_a1(&node),
        0x0012 => visitor.on_variable_expr_a2(&node),
        0x0013 => visitor.on_variable_expr_a3(&node),
        0x0014 => visitor.on_variable_expr(&node),
        0x0015 => visitor.on_variable_expr_v1(&node),
        0x0016 => visitor.on_variable_expr_v2(&node),
        0x0017 => visitor.on_variable_expr_v3(&node),
        0x0018 => visitor.on_variable_expr_v4(&node),
        0x0019 => visitor.on_variable_expr_v5(&node),
        0x001A => visitor.on_variable_expr_v6(&node),
        0x001B => visitor.on_variable_expr_v7(&node),
        0x001C => visitor.on_variable_expr_v8(&node),
        0x001D => visitor.on_variable_function(&node),
        0x001E => visitor.on_variable_aggregate(&node),
        0x001F => visitor.on_variable_function_expr(&node),
        0x0020 => visitor.on_variable_function_expr_v1(&node),
        0x0021 => visitor.on_variable_function_expr_v2(&node),
        0x0022 => visitor.on_variable_function_expr_v3(&node),
        0x0023 => visitor.on_variable_function_expr_v4(&node),
        0x0024 => visitor.on_variable_function_expr_v5(&node),
        0x0025 => visitor.on_variable_function_expr_v6(&node),
        0x0026 => visitor.on_variable_function_expr_v7(&node),
        0x0027 => visitor.on_variable_function_expr_v8(&node),
        0x0028 => visitor.on_variable_member(&node),
        _ => ()
    };
}
